### ISSUE TITLE
华为函数工作流跨域报错

### ISSUE THREAD

**Issue by Hinghuai** [zzc10086/grocery_store#11]
已添加localurl和accesskey
脚本运行时出现如下错误
![微信截图_20211106004350](https://user-images.githubusercontent.com/63064333/140547163-b19c9d90-a0eb-4864-adaf-ce73b153c338.png)

`Access to XMLHttpRequest at 'https://b20d13fc1e834e148f2cb3d997be2334.apig.ap-southeast-2.huaweicloudapis.com/biliapi/?access_key=74beb9b934cfeb9bcf7dc4b2d0ff4aa1&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=279785156&device=android&ep_id=376384&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=120&track_path=0&ts=1636130189&sign=835263d2ee99f61d40a5e3c30692bf22' from origin 'https://www.bilibili.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`
大佬，实在不会了，求助

**Comment by zzc10086** [comment]
跨域问题需要在请求的时候带上referer字段且chrome要求同为https链接
你也可以修改https://github.com/zzc10086/grocery_store/blob/35ecdbd4811ed1917f110949026f84b5695bb23a/bili_proxy/251_FunctionGraph_BPplayurl-for-Thailand.php#L136
为
`$response_headers['access-control-allow-origin'] = "https://www.bilibili.com/";`

**Comment by Hinghuai** [comment]
好的，谢谢dalao
跨域问题解决了
