### ISSUE TITLE
如果是用Google Cloud的云函数的话用哪个脚本啊

### ISSUE THREAD

**Issue by SpectreAX** [zzc10086/grocery_store#12]
或者现有的脚本该怎么修改

**Comment by SpectreAX** [comment]
已掌握.
这个就行https://github.com/zzc10086/grocery_store/blob/master/bili_proxy/BPplayurl.php

**Comment by banana-suisei** [comment]
> 已掌握. 这个就行https://github.com/zzc10086/grocery_store/blob/master/bili_proxy/BPplayurl.php

请问那个入口点要怎么填

**Comment by SpectreAX** [comment]
> > 已掌握. 这个就行https://github.com/zzc10086/grocery_store/blob/master/bili_proxy/BPplayurl.php
> 
> 请问那个入口点要怎么填

填 / 就行 记得在触发器URL后面加上/playurl

**Comment by SpectreAX** [comment]
顺便说一下GCP的云函数的域名被墙了 如果肉身在国内可能还是阿里腾讯云方便一点

**Comment by banana-suisei** [comment]
> 顺便说一下GCP的云函数的域名被墙了 如果肉身在国内可能还是阿里腾讯云方便一点

谢谢，整好了，我把它作为一个能直连的香港服务器的解析API，主要是台湾的服务器有点难找或者太贵了，所以才用谷歌的

**Comment by SpectreAX** [comment]
OK

**Comment by yanxijian** [comment]
> > > 已掌握. 这个就行https://github.com/zzc10086/grocery_store/blob/master/bili_proxy/BPplayurl.php
> > 
> > 
> > 请问那个入口点要怎么填
> 
> 填 / 就行 记得在触发器URL后面加上/playurl

你好，那个入口点函数是真的填 / 就好了吗？用这个好像会报错
```
2022-07-22T17:27:43.189707Zbilibili4pgiw0ondip3 [22-Jul-2022 17:27:43] WARNING: [pool app] child 20 said into stderr: "PHP message: PHP Fatal error: Uncaught InvalidArgumentException: Function target is not callable: "/" in /workspace/vendor/google/cloud-functions-framework/router.php:53"
[22-Jul-2022 17:27:43] WARNING: [pool app] child 20 said into stderr: "PHP message: PHP Fatal error: Uncaught InvalidArgumentException: Function target is not callable: "/" in /workspace/vendor/google/cloud-functions-framework/router.php:53"
```

Update：
用了下面这位大佬修改的，搞定了
https://github.com/Admirepowered/bilibli-proxy

**Comment by wudifeixue** [comment]
> 

这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了

![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png)
![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)

**Comment by SpectreAX** [comment]
> > 
> 
> 这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了
> 
> ![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png) ![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)

用公共的解析服务器吧，我之前也找了好久，最后发现只有一些台湾本地的云服务商有台湾的机子，价格还不便宜。
PS：之前有看到新闻说微软要在台湾建数据中心，以后Azure可能会有台湾服务器吧，如果坚持要自建的话，可以后续关注一下。

**Comment by wudifeixue** [comment]
> > > 
> > 
> > 
> > 这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了
> > ![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png) ![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)
> 
> 用公共的解析服务器吧，我之前也找了好久，最后发现只有一些台湾本地的云服务商有台湾的机子，价格还不便宜。 PS：之前有看到新闻说微软要在台湾建数据中心，以后Azure可能会有台湾服务器吧，如果坚持要自建的话，可以后续关注一下。

诶，公共的，我试了，基本全都不能用了。。所以才去尝试自建，好像都扛不住压力被用爆了。。

**Comment by banana-suisei** [comment]
> > 
> 
> 这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了
> 
> ![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png) ![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)

可以拿一台没被墙的机子中转一下

**Comment by SpectreAX** [comment]
> > > > 
> > > 
> > > 
> > > 这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了
> > > ![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png) ![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)
> > 
> > 
> > 用公共的解析服务器吧，我之前也找了好久，最后发现只有一些台湾本地的云服务商有台湾的机子，价格还不便宜。 PS：之前有看到新闻说微软要在台湾建数据中心，以后Azure可能会有台湾服务器吧，如果坚持要自建的话，可以后续关注一下。
> 
> 诶，公共的，我试了，基本全都不能用了。。所以才去尝试自建，好像都扛不住压力被用爆了。。

https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8 第一个 我试了可以用的

**Comment by yanxijian** [comment]
> 

还是要看价格，香港阿里云是3.5刀，台湾GCP就是5刀起步了，贵了不少，Azure 的话如果价格没优势也是不行啊

**Comment by wudifeixue** [comment]
> 

这个，怎么做其实有点不太会，我也想这么试试来的，但是想让油猴脚本继续工作是难点

**Comment by wudifeixue** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这个，我今天把所有大云(Azure, aws, 阿里，腾讯，华为，IBM，Oracle，谷歌）都看了一遍，貌似只有谷歌有台区的服务器，而这个又被国内给墙了，有点尴尬啊，有没有办法解决这新的难题，毕竟好几个新番开始只允许台区看了
> > > > ![image](https://user-images.githubusercontent.com/7316929/211952706-1b888db4-9fa8-4897-994e-0905fe82610a.png) ![image](https://user-images.githubusercontent.com/7316929/211952823-a4d5078f-c7d1-4f85-a2f5-93f50ad4f900.png)
> > > 
> > > 
> > > 用公共的解析服务器吧，我之前也找了好久，最后发现只有一些台湾本地的云服务商有台湾的机子，价格还不便宜。 PS：之前有看到新闻说微软要在台湾建数据中心，以后Azure可能会有台湾服务器吧，如果坚持要自建的话，可以后续关注一下。
> > 
> > 
> > 诶，公共的，我试了，基本全都不能用了。。所以才去尝试自建，好像都扛不住压力被用爆了。。
> 
> https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8 第一个 我试了可以用的

噢噢，确实可以，不错

**Comment by wudifeixue** [comment]
> > 
> 
> 还是要看价格，香港阿里云是3.5刀，台湾GCP就是5刀起步了，贵了不少，Azure 的话如果价格没优势也是不行啊

每一家函数都给免费白嫖，所以其实都没花一分钱233
