### ISSUE TITLE
根据教程在阿里云粘贴Php程序运行后，Response: Failed to match interface.

### ISSUE THREAD

**Issue by JianHua-Deng** [zzc10086/grocery_store#14]
Log Output: 
FunctionCompute php7.2 runtime inited.
FC Invoke Start RequestId: 8d57ae15-b1d1-482e-a3b3-8b4ae55dea2f
\nFC Invoke End RequestId: 8d57ae15-b1d1-482e-a3b3-8b4ae55dea2f

在这方面纯小白，不太清楚发生了什么。
根据教程，页面底下应该会有一个网址的，但我实在什么都没看到。
![image](https://user-images.githubusercontent.com/72770907/194975270-af0f7141-b807-462e-b72b-76f4089d980a.png)
![image](https://user-images.githubusercontent.com/72770907/194975279-055edae6-4c00-4e7f-bae4-e4de242212b6.png)

**Comment by zzc10086** [comment]
返回Failed to match interface.是正常的.

**Comment by JianHua-Deng** [comment]
> 返回Failed to match interface.是正常的.

那请问用来反代的http地址是在哪里可以找到呢？说是在页面的下方但我实在没找到，在其他页面找到的地址我也不确定是哪一个。
![image](https://user-images.githubusercontent.com/72770907/195187263-1ebd95e2-6023-4b1b-bd3e-6d3dbdee72e7.png)

**Comment by zzc10086** [comment]
![QQ截图20221012040520](https://user-images.githubusercontent.com/50003754/195187993-66a53aac-600e-4535-bca9-779f344c91e0.png)
红框里的地址填到代理服务器即可

**Comment by JianHua-Deng** [comment]
> ![QQ截图20221012040520](https://user-images.githubusercontent.com/50003754/195187993-66a53aac-600e-4535-bca9-779f344c91e0.png) 红框里的地址填到代理服务器即可

啊原来如此，现在好了，谢谢！
