### ISSUE TITLE
脚本返回502 bad gateway

### ISSUE THREAD

**Issue by swhoro** [zzc10086/grocery_store#15]
![无标题](https://user-images.githubusercontent.com/34229589/199266906-63a80cfb-746a-441c-8a87-77198af1f2cb.png)

**Comment by zzc10086** [comment]
返回的内容是啥

**Comment by swhoro** [comment]
> 返回的内容是啥

Failed to match interface.

**Comment by zzc10086** [comment]
升级油猴脚本到最新版本或者在链接后面添加playurl，[具体操作在已关闭的issue里面有](https://github.com/ipcjs/bilibili-helper/issues/710#issuecomment-877824151)

**Comment by swhoro** [comment]
> 升级油猴脚本到最新版本或者在链接后面添加playurl，[具体操作在已关闭的issue里面有](https://github.com/ipcjs/bilibili-helper/issues/710#issuecomment-877824151)

好像还是有问题
之前我用的是edge + edge拓展市场里面的油猴，好像edge版的一直没更新，所以我用的加playurl方式解决
但是现在我用的是edge和googl市场里面的油猴，貌似还是不行还是得加playurl才行
edge：108.0.1462.46 (正式版本) (64 位)
TamperMonkey：4.18.1

**Comment by zzc10086** [comment]
脚本日志贴一下

**Comment by swhoro** [comment]
> 脚本日志贴一下

![image](https://user-images.githubusercontent.com/34229589/206909994-1fbe830c-339d-4bea-a7af-7a01d7ac3de6.png)

**Comment by zzc10086** [comment]
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
```
![image](https://user-images.githubusercontent.com/50003754/206910360-7c11904b-d141-4be3-ab95-53fc079542d0.png)

**Comment by swhoro** [comment]
> ```
> 点击“设置 > 复制日志”，将导出的日志，粘贴在这里
> （设置按钮在番剧页面的右下角，是一个“土星”图标）
> ```
> 
> ![image](https://user-images.githubusercontent.com/50003754/206910360-7c11904b-d141-4be3-ab95-53fc079542d0.png)

不好意思

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss43177?spm_id_from=..0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"狼in约伊兹","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=43177
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?cid=843971084&qn=112&type=&otype=json&fourk=1&bvid=BV1Ne4y1H77u&ep_id=681431&fnver=0&fnval=80&session=bc1ba05420b57020bf7294159ffd4e79&module=bangumi&area=hk
debug: atRun: 2, complete
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1841964069062455.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/bili.LATEST/bili/?cid=843971084&qn=112&type=&otype=json&fourk=1&bvid=BV1Ne4y1H77u&ep_id=681431&fnver=0&fnval=80&session=bc1ba05420b57020bf7294159ffd4e79&module=bangumi
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?cid=843971084&qn=112&type=&otype=json&fourk=1&bvid=BV1Ne4y1H77u&ep_id=681431&fnver=0&fnval=80&session=bc1ba05420b57020bf7294159ffd4e79&module=bangumi&area=cn
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key={{access_key}}&appkey=7d089525d3611b1c&area=th&build=1001310&cid=843971084&ep_id=681431&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1670769934&sign=d77a80e16e9a68dc868d114dcfa9b80b
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?cid=843971084&qn=112&type=&otype=json&fourk=1&bvid=BV1Ne4y1H77u&ep_id=681431&fnver=0&fnval=80&session=bc1ba05420b57020bf7294159ffd4e79&module=bangumi&area=tw
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?avid=undefined&cid=843971084&bvid=BV1Ne4y1H77u&qn=112&type=&otype=json&ep_id=681431&fourk=1&fnver=0&fnval=80&session=7efa5d8214ceee1c66d4ad9f028c507a&module=bangumi&balh_ajax=1&area=hk
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1841964069062455.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/bili.LATEST/bili/?avid=undefined&cid=843971084&bvid=BV1Ne4y1H77u&qn=112&type=&otype=json&ep_id=681431&fourk=1&fnver=0&fnval=80&session=7efa5d8214ceee1c66d4ad9f028c507a&module=bangumi&balh_ajax=1
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?avid=undefined&cid=843971084&bvid=BV1Ne4y1H77u&qn=112&type=&otype=json&ep_id=681431&fourk=1&fnver=0&fnval=80&session=7efa5d8214ceee1c66d4ad9f028c507a&module=bangumi&balh_ajax=1&area=cn
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=undefined&appkey=7d089525d3611b1c&area=th&build=1001310&cid=843971084&ep_id=681431&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1670769936&sign=765a92f7f7fb91a19314ca15f30f6c23
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?avid=undefined&cid=843971084&bvid=BV1Ne4y1H77u&qn=112&type=&otype=json&ep_id=681431&fourk=1&fnver=0&fnval=80&session=7efa5d8214ceee1c66d4ad9f028c507a&module=bangumi&balh_ajax=1&area=tw
debug: /x/web-interface/nav {"uname":"狼in约伊兹","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

**Comment by zzc10086** [comment]
这个阿里云的代理时你自己搭建的吗?确定还能够使用?

**Comment by swhoro** [comment]
> 这个阿里云的代理时你自己搭建的吗?确定还能够使用?

是我自己弄得
加了playurl之后能够正常使用

**Comment by zzc10086** [comment]
![image](https://user-images.githubusercontent.com/50003754/206912661-6ac33d63-09ea-4752-94a6-5eb299b1b7ff.png)
脚本会判断代理服务器链接是否标准,之前的阿里云的代理链接是不符合这个条件的.目前阿里云那边做了更新是可以直接用了,你把旧的删了重新建一个就行了

**Comment by swhoro** [comment]
> ![image](https://user-images.githubusercontent.com/50003754/206912661-6ac33d63-09ea-4752-94a6-5eb299b1b7ff.png) 脚本会判断代理服务器链接是否标准,之前的阿里云的代理链接是不符合这个条件的.目前阿里云那边做了更新是可以直接用了,你把旧的删了重新建一个就行了

ok了，谢谢

**Comment by nyavana** [comment]
**更新：切换回旧版页面，问题解决了**

hi, 需要从国外翻回来，edge和Firefox同配置均无法播放，脚本最新，相同错误，加上/playurl也无法播放：

![image](https://github.com/zzc10086/grocery_store/assets/33804090/7b80b60d-dc21-4f0c-90f3-bbdf0abdb3a3)

阿里云UI更新了，这是我按照简易教程找到的链接地址，但是和教程上的格式不一样：

![Screenshot 2023-10-11 180441](https://github.com/zzc10086/grocery_store/assets/33804090/d279eec2-adac-47df-b35a-b4bcdfa6e722)

填入链接时有小勾：

![image](https://github.com/zzc10086/grocery_store/assets/33804090/7a83c29a-0a25-44c3-a7b8-ce1bcc6f00ae)
