### ISSUE TITLE
无法授权大会员

### ISSUE THREAD

**Issue by nkjcqvcpi** [zzc10086/grocery_store#18]
在阿里云部署，油猴插件点击账号授权，弹出页面显示“正在获取授权，请稍候……”，无跳转或返回，打开大会员番剧，报错

## 拉取视频地址失败
原因: {"code":6002105,"message":"开通大会员观看"}

**Comment by nkjcqvcpi** [comment]
B站的MCBBS接口关掉了，如何将SESSDATA加到请求的header中

**Comment by zzc10086** [comment]
我的会员月初过期了,测不了,给你个方法试试.
打开MCBBS的[新接口](https://passport.bilibili.com/register/pc_oauth2.html#/?response_type=code&redirect_uri=&client_id=b76c464299d5573f&return_url=https%3A%2F%2Fbeta.mcbbs.net%2Flogin%2Foauth%2Fbilibili%3Ftype%3Dlogin),按流程登录授权后会跳转到`https://beta.mcbbs.net/login/oauth/bilibili?code=xxxxxxxxxxxxxxxxxxx&state=&type=login`,把code复制到access_key试试

**Comment by nkjcqvcpi** [comment]
> 我的会员月初过期了,测不了,给你个方法试试. 打开MCBBS的[新接口](https://passport.bilibili.com/register/pc_oauth2.html#/?response_type=code&redirect_uri=&client_id=b76c464299d5573f&return_url=https%3A%2F%2Fbeta.mcbbs.net%2Flogin%2Foauth%2Fbilibili%3Ftype%3Dlogin),按流程登录授权后会跳转到`https://beta.mcbbs.net/login/oauth/bilibili?code=xxxxxxxxxxxxxxxxxxx&state=&type=login`,把code复制到access_key试试

这个code可行：）
