### ISSUE TITLE
请问只需要把BPplayurl.php上传到PHP空间就行了吗？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [zzc10086/grocery_store#3]

**Comment by zzc10086** [comment]
还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索

**Comment by yubanmeiqin9048** [comment]
> 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索

大佬，请恕我愚钝，前面的我都理解，就是这个正则^(.*)playurl(.*)$应该写到哪里？我摸索了好一会发现还是搞不太明白

**Comment by zzc10086** [comment]
> > 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索
> 
> 大佬，请恕我愚钝，前面的我都理解，就是这个正则^(._)playurl(._)$应该写到哪里？我摸索了好一会发现还是搞不太明白

一般虚拟主机的面板都有地址映射，可能名字不叫这个，你可以发个工单问下客服
![Screenshot_20201223-091511_Browser](https://user-images.githubusercontent.com/50003754/102948119-189a1600-4500-11eb-8fa9-9bda1aa3f318.png)

**Comment by yubanmeiqin9048** [comment]
> > > 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索
> > 
> > 大佬，请恕我愚钝，前面的我都理解，就是这个正则^(._)playurl(._)$应该写到哪里？我摸索了好一会发现还是搞不太明白
> 
> 一般虚拟主机的面板都有地址映射，可能名字不叫这个，你可以发个工单问下客服
> ![Screenshot_20201223-091511_Browser](https://user-images.githubusercontent.com/50003754/102948119-189a1600-4500-11eb-8fa9-9bda1aa3f318.png)
> 

行吧，我问了下客服解决了，但是怎么样判断有没有搭建成功呢？我直接访问搭建好的服务器浏览器显示{"code":-400,"message":"请求错误"}，放到脚本里面也无法拉取视频，是不是因为我没有安装ssl证书的原因？

**Comment by zzc10086** [comment]
> > > > 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索
> > > 
> > > 
> > > 大佬，请恕我愚钝，前面的我都理解，就是这个正则^(._)playurl(._)$应该写到哪里？我摸索了好一会发现还是搞不太明白
> > 
> > 
> > 一般虚拟主机的面板都有地址映射，可能名字不叫这个，你可以发个工单问下客服
> > ![Screenshot_20201223-091511_Browser](https://user-images.githubusercontent.com/50003754/102948119-189a1600-4500-11eb-8fa9-9bda1aa3f318.png)
> 
> 行吧，我问了下客服解决了，但是怎么样判断有没有搭建成功呢？我直接访问搭建好的服务器浏览器显示{"code":-400,"message":"请求错误"}，放到脚本里面也无法拉取视频，是不是因为我没有安装ssl证书的原因？

应该不是证书问题，你直接请求没有带参数吗？要把原来b站请求的链接的参数拼接在后面

**Comment by yubanmeiqin9048** [comment]
> > > > > 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索
> > > > 
> > > > 
> > > > 大佬，请恕我愚钝，前面的我都理解，就是这个正则^(._)playurl(._)$应该写到哪里？我摸索了好一会发现还是搞不太明白
> > > 
> > > 
> > > 一般虚拟主机的面板都有地址映射，可能名字不叫这个，你可以发个工单问下客服
> > > ![Screenshot_20201223-091511_Browser](https://user-images.githubusercontent.com/50003754/102948119-189a1600-4500-11eb-8fa9-9bda1aa3f318.png)
> > 
> > 
> > 行吧，我问了下客服解决了，但是怎么样判断有没有搭建成功呢？我直接访问搭建好的服务器浏览器显示{"code":-400,"message":"请求错误"}，放到脚本里面也无法拉取视频，是不是因为我没有安装ssl证书的原因？
> 
> 应该不是证书问题，你直接请求没有带参数吗？要把原来b站请求的链接的参数拼接在后面

感谢大佬的回答，我再自己摸索下吧，能否告知大佬所用的PHP空间是哪一家

**Comment by zzc10086** [comment]
> > > > > > 还需要绑定域名和证书,如果空间提供商有就可以用他的,应该也有免费的.然后写一个正则`^(.*)playurl(.*)$`把传过来的请求映射到BPplayurl.php上.由于每个空间提供商操作都不同,详细步骤请自行摸索
> > > > > 
> > > > > 
> > > > > 大佬，请恕我愚钝，前面的我都理解，就是这个正则^(._)playurl(._)$应该写到哪里？我摸索了好一会发现还是搞不太明白
> > > > 
> > > > 
> > > > 一般虚拟主机的面板都有地址映射，可能名字不叫这个，你可以发个工单问下客服
> > > > ![Screenshot_20201223-091511_Browser](https://user-images.githubusercontent.com/50003754/102948119-189a1600-4500-11eb-8fa9-9bda1aa3f318.png)
> > > 
> > > 
> > > 行吧，我问了下客服解决了，但是怎么样判断有没有搭建成功呢？我直接访问搭建好的服务器浏览器显示{"code":-400,"message":"请求错误"}，放到脚本里面也无法拉取视频，是不是因为我没有安装ssl证书的原因？
> > 
> > 
> > 应该不是证书问题，你直接请求没有带参数吗？要把原来b站请求的链接的参数拼接在后面
> 
> 感谢大佬的回答，我再自己摸索下吧，能否告知大佬所用的PHP空间是哪一家

商家就不发了，小商家怕人去多了会跑路。可以去hostloc论坛里面找找，我这个也是在里面找的
