### ISSUE TITLE
请问能介绍一下解除限制脚本腾讯云函数怎么操作吗

### ISSUE THREAD

**Issue by swhoro** [zzc10086/grocery_store#5]
找了半天都不知道腾讯云的HTTP函数在哪里，哭了，刚接触云函数这个东西
阿里云也有一个，但是不知道为什么总是卡在“加载视频内容”，然后就是服务器返回异常，可能是我家的网与阿里云服务器不太好？
用其它公共的代理服务器倒是可以正常观看
不会php，只懂一点python...

**Comment by zzc10086** [comment]
浏览器按F12查看控制台的具体报错内容,看代理服务器是否正常返回视频流地址

**Comment by swhoro** [comment]
> 浏览器按F12查看控制台的具体报错内容,看代理服务器是否正常返回视频流地址

![无标题](https://user-images.githubusercontent.com/34229589/104149816-a76cc500-5412-11eb-8457-1b0839640956.png)

**Comment by zzc10086** [comment]
注意隐藏链接，请求超过限额可能会产生费用
这个报错和代理服务器没关系，视频地址正常返回了。我这边用你的地址可以播放
![Uploading QQ截图20210111161115.png…]()

**Comment by zzc10086** [comment]
注意隐藏链接，请求超过限额可能会产生费用
这个报错和代理服务器没关系，视频地址正常返回了。我这边用你的地址可以播放

**Comment by zzc10086** [comment]
[腾讯云函数](https://console.cloud.tencent.com/scf/list)
腾讯云函数大概流程说下:点击新建,自定义创建,选择php7运行环境,选择地区,粘贴php代码.自定义触发器配置,触发方式api网关,请求方法get.点击完成即可.代理链接在触发管理中获取

**Comment by swhoro** [comment]
> [腾讯云函数](https://console.cloud.tencent.com/scf/list)
> 腾讯云函数大概流程说下:点击新建,自定义创建,选择php7运行环境,选择地区,粘贴php代码.自定义触发器配置,触发方式api网关,请求方法get.点击完成即可.代理链接在触发管理中获取

又出现新的问题了
刚才试了一下，填阿里云函数的链接的话巨人的番剧页面和播放页面都会显示出错啦，填腾讯云函数的话番剧页面可以进，但是播放页面也是出错啦
试了下部分其他的港澳台（JOJO 幼女战记 政宗君的复仇）可以正常打开并观看

**Comment by zzc10086** [comment]
巨人限制为台湾地区,云函数目前只提供了大陆和香港.除非你有台湾的代理服务器.进击第二季貌似用了新的屏蔽方法,等脚本更新吧
