### ISSUE TITLE
港澳台区域的番剧，也可以用大佬的脚本突破区域限制吗？

### ISSUE THREAD

**Issue by lgc1993-CN** [zzc10086/grocery_store#8]
RT，在阿里云的香港Region弄了个函数，好像不起作用，是不是需要其他操作？

**Comment by zzc10086** [comment]
油猴脚本用ipcjs原版的话需要在链接后面加playurl  
如果油猴脚本也用我这边魔改的话应该没有问题,可反馈油猴脚本日志和浏览器控制台日志,我看下

**Comment by verity886** [comment]
一样的问题，貌似是函数的HTTP地址打不开
![image](https://user-images.githubusercontent.com/37663967/125655819-f9472e22-c172-4d65-9964-ee779f322db5.png)

![_E$U~H7C%(SX8QY82YQJLBW](https://user-images.githubusercontent.com/37663967/125655357-27a567f8-a39f-44c4-b189-d08939f2e9cb.png)

但是服务器地址本身是可以打开的

![image](https://user-images.githubusercontent.com/37663967/125655645-5f490585-58dc-488d-9e4f-1baa3f783613.png)

**Comment by zzc10086** [comment]
@verity886 没添加playurl

**Comment by verity886** [comment]
> @verity886 没添加playurl

请问如何添加，需要修改代码吗

**Comment by zzc10086** [comment]
@verity886 [这里](https://github.com/ipcjs/bilibili-helper/issues/710#issuecomment-877824151)
