### ISSUE TITLE
海外想翻回大陆出现这个怎办

### ISSUE THREAD

**Issue by Lianye-Scythe** [zzc10086/grocery_store#9]
## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":4,"responseText":"{\"ErrorCode\":\"InvalidArgument\",\"ErrorMessage\":\"The role not exists: acs:ram::5215927400*****9:role/aliyunfcdefaultrole. \"}","status":400,"statusText":"Bad Request"}}
自建的阿里云计算，用的最新脚本也加了/playurl
解除B站区域限制 用的是v8.2.4

**Comment by zzc10086** [comment]
应该和阿里云的权限配置有关.需要给账号授予AliyunFCDefaultRole权限

**Comment by zzc10086** [comment]
你访问[这个链接](https://fc.console.aliyun.com/fc/overview)应该会弹出授权页面

**Comment by Lianye-Scythe** [comment]
> 你访问[这个链接](https://fc.console.aliyun.com/fc/overview)应该会弹出授权页面

哦哦，同意后成功了!感谢大大
